---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: false
  kubeProxyMode: "ipvs"

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
        listenAddress: "0.0.0.0"
    #image:
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "deployment=KIND"
    extraMounts:
      - hostPath: /mnt/kind/config/hostpath-provisioner.yaml
        containerPath: /kind/manifests/default-storage.yaml
      - hostPath: /mnt/kind/hostpath-provisioner
        containerPath: /tmp/hostpath-provisioner

  - role: worker
    #image:
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "deployment=KIND"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: "0.0.0.0"
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: "0.0.0.0"
    extraMounts:
      - hostPath: /mnt/kind/hostpath-provisioner
        containerPath: /tmp/hostpath-provisioner
