---
apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  annotations:
  generation: 3
  name: atlassian-test
  namespace: demo
spec:
  distribution: null
  version: v1.21
  settings:
    network:
      cni:
        name: calico
      pods:
        cidrBlocks:
          - 192.172.0.0/24
      proxy:
        httpProxy: http://192.168.156.10:3128
        httpsProxy: http://192.168.156.10:3128
        noProxy:
          - 172.16.0.0/16
          - 172.17.0.0/16
          - 172.18.0.0/16
          - 10.96.0.0/12
          - 192.172.0.0/24
          - localhost
          - 127.0.0.1
      serviceDomain: cluster.local
      services:
        cidrBlocks:
          - 10.96.0.0/12
      trust:
        additionalTrustedCAs:
          - data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlHQkRDQ0EreWdBd0lCQWdJVUVzN3EyNTNQZGYyd1ZBOTkxZ0NWQUVRK1JTa3dEUVlKS29aSWh2Y05BUUVODQpCUUF3YlRFTE1Ba0dBMVVFQmhNQ1EwNHhEREFLQmdOVkJBZ01BMEZEVkRFUk1BOEdBMVVFQnd3SVEyRnVZbVZ5DQpjbUV4RFRBTEJnTlZCQW9NQkVSRFUwVXhEVEFMQmdOVkJBc01CRVJEVTBVeEh6QWRCZ05WQkFNTUZtaGhjbUp2DQpjaTV3YjJNdVpHTnpaUzV0YVd3dVlYVXdIaGNOTWpNd01qSXdNakV5T1RNeldoY05Nek13TWpFM01qRXlPVE16DQpXakJ0TVFzd0NRWURWUVFHRXdKRFRqRU1NQW9HQTFVRUNBd0RRVU5VTVJFd0R3WURWUVFIREFoRFlXNWlaWEp5DQpZVEVOTUFzR0ExVUVDZ3dFUkVOVFJURU5NQXNHQTFVRUN3d0VSRU5UUlRFZk1CMEdBMVVFQXd3V2FHRnlZbTl5DQpMbkJ2WXk1a1kzTmxMbTFwYkM1aGRUQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCDQpBS3F6ak1VZHpPb0dTUTU1cjFUSkVGbWhORVRkQ3dpUTRVS3J6MWtJQ3pBSTh0WGZUOGJ3aUwva0laRWNidjhuDQpENi9qcEhMR1JsMFRpV0VzQXltZVRET0V0UEdUblBYNGJEdllDcGJpTVRqb3dJZlhCVmZKZmY1b3BNem9LK0NsDQp2Q2pZeTJuKy9BVWxFY3pGOWhBL0VpZlM2YnlOc04xeWpOTmt5enZ6OEJMWkxyWFhFa1laQUQvTnhDaFpMYUVwDQpsOGpBZkRuQi9KL2dveSs5UmNYTXc1dDJOZDhSeTM3d1A4SGNmSExZOVZQOVV5NTFHMGZLcFpjU3Z2K0F4VlpDDQphYm9yTk81dWRiMUtCYUZBV29odE1rUmRRSEl1bTRzbjJ3R2hpRE9DaFdEY1FmRlV0eGQrTDJiUnVLZ2tHWFVKDQp5RGtqYlN4cVI3d250NjNobmR6aDJ5SGduemFMdWR3QVBWWmRYNko4cmNTajJIN1l2T1FqVGJ3aXlzWWhnRExNDQp6L25MS2JkZFprMTQ1aVhhbzVnTzNJY1ZKcWd6ZE42VlYrN0k1UVNhblhmUTBtaDBzU1dTN3A0Wm5hZkdQTFJvDQp3WHZtRlhMTGFHSzZ2T256LzhTamx1Mlp0U1U4V0xsWURBOE14TVFQbGUwU1RBODZ4dzlzTHRCOUdNVXh1dnluDQplWDM2Qk92TGNHRVBoOFpvSlQ4czcxMk53ZjR0dXhNdk4vYW16aWNDanNKaHZBcTVRQXlzU1ZJSGdGQVFDMXkwDQo2WFFUYmtqY1J1WmEvYzBmV3gwL25rc3d3OTZrRVNaR3pTTzc5YmVYT0pVcU42L2VqcDRpTjQ3YUh1NkNCc2pIDQpUYzBKT0ZTTys4K3ZvSDlJdjFXTExqNnNaT1RVelBWKy8wb1FVYXJhNVA3YkFnTUJBQUdqZ1pzd2daZ3dId1lEDQpWUjBqQkJnd0ZvQVVJcWx4VGFsbDFYREczbzY3RHlQQVlvUFlpa3N3Q1FZRFZSMFRCQUl3QURBTEJnTlZIUThFDQpCQU1DQlBBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdLUVlEVlIwUkJDSXdJSUlXYUdGeVltOXlMbkJ2DQpZeTVrWTNObExtMXBiQzVoZFlJR2FHRnlZbTl5TUIwR0ExVWREZ1FXQkJSMU12ejEwVTBlNThjRkk0WUxacmhJDQpMYnExT3pBTkJna3Foa2lHOXcwQkFRMEZBQU9DQWdFQU1oQjZsdjQxREIrQjF2L3NIcDZSUTVwRkhmZHFYaThaDQppbEtlc1l4N1B2c3VjQytvRUUxdVZLa2RsS09XVDN3cVVLL2VadEhxWUVqTEk4RlB2VzlXS1oyK3U1WElLMTFMDQpZMk1VSEtjYnMxUmZnT2FIK1JJYktxbmgranNkek1IRHltVFF5OE85SnhGYVdZNnhCRnVWeXB4dlNiWXhveWRlDQp2L2w4WWY1MzhRcTdxMlFhOWQxU1pmUHBhN0g5a3FueWVKQzdES3R3ajFYeWFkRzFiM09XZERFbHorMGY0M2pODQpQc2FGdlFGZDE4QkFKSmlkclNvYnNmUUx5RytVQ3ZZRnpPcEtXNWRuTjdoUDYvTHRqSDQvRWtURjVUV1IyUW13DQo5V0NRclZVZXBLMzlvVkRXTSs5alhzWEdCT1VkRisxUTlHeG9rM0l0U0NDSmlWcWgra2dKdHlLd2dyMHpJVncxDQpoc2Foai93UVdEVXk0MGFxSzBOSURUbVBrN1N3SVZtdHZFMlpFVmJ1NlV1SEFOamFMYlNUNW5kMmVwZDR4K3BCDQp6VDZyTjBUcVlHVG9DVWdEQytiSkJIakkyKzIzbmd2UllQbmdWR29EdGpNWmFaR2NWZW1xRWdCRDQ2UW91Y2tjDQplZk42NCt3T0VNRDB6bDMxaGxDN3FZMWlMWmV2aG5jdmlqcUcvT3dqaXkyYjdEN3Z4Z3BSMEpJcm5iWlNUVlgyDQoySzB1dGM5a3pENnd1V2ZzRzdEWnh1UFU2NGJGWGI2Rmw3cEJrdGQ4eVUvbC9tZEFQWUF5SzJPNmttOEhaOUp0DQpIbmdZVzNER2V5U2lVUStudE1QaS9wY21xTVU3YjdUTy9rZEVieTlMUkZ4Z295VFRTaFdFZnhKYk1XbjVMSldFDQpTOUs0TCtERVFPST0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg==
            name: harbor
          - data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGSERDQ0JBU2dBd0lCQWdJRUQvNEFIekFOQmdrcWhraUc5dzBCQVFzRkFEQjFNUXN3Q1FZRFZRUUdFd0pCDQpWVEVNTUFvR0ExVUVDQk1EUVVOVU1ROHdEUVlEVlFRSEV3WklZWEp0WVc0eEhqQWNCZ05WQkFvVEZVUmxjR0Z5DQpkRzFsYm5RZ2IyWWdSR1ZtWlc1alpURU5NQXNHQTFVRUN4TUVSRk5QUXpFWU1CWUdBMVVFQXhNUGFYQmhMbVJqDQpjMlV1Yldsc0xtRjFNQjRYRFRJeU1Ea3lOekExTVRNek4xb1hEVEkwTURreU56QTFNVE16TjFvd09URVVNQklHDQpBMVVFQ2d3TFJFTlRSUzVOU1V3dVFWVXhJVEFmQmdOVkJBTU1HR2hoY25CMk1EQmlhWFF3TVM1a1kzTmxMbTFwDQpiQzVoZFRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWtlV1YvZjJCSDVEMzdnDQp2ZUV1SStMczZveGJjTUJzd1ZIRFovTmhPL01ubjcxSGhySzdhOCtINC8veC9mYnV2T01ibmo3M0paTFczT3N6DQphcjJldHBwU1hqR3dZWkp6SVhmU1dSUCtySm1URHorSlN2WWNINDdtdXFzd3pLQlNRMFZtV3lJdjRIdHVHZkFJDQowa0d6YitvSmpKdmhGMlVzNnYvVEV0aUE5WE1mRmdneEVJY0IwaUl5TEZ5WjFzTUJpZitoYU5WdVpjdXR3T09vDQoyUGl5amlwMUhpQVV1ekRQRkw2RUFjNnRaUWtkZjhqZVBHMEUvdk45Vkg2TVlnOXZrR1pTSVhrVlhjOGRSM2dlDQo0dXRoaEdvZWROR25VbTkycHU5eW5Fd054ZVYwSHNvaU9rY1FzWDVLeklvei9JbGpiVDhZeXN2SmFPc0dsQ0FwDQpFYXFtMGxNQ0F3RUFBYU9DQWU0d2dnSHFNQjhHQTFVZEl3UVlNQmFBRkhNZFJoWC9wMlp5WFY4NG1yVVhzbFZUDQpGRkk4TUQwR0NDc0dBUVVGQndFQkJERXdMekF0QmdnckJnRUZCUWN3QVlZaGFIUjBjRG92TDJsd1lTMWpZUzVrDQpZM05sTG0xcGJDNWhkUzlqWVM5dlkzTndNQTRHQTFVZER3RUIvd1FFQXdJRThEQWRCZ05WSFNVRUZqQVVCZ2dyDQpCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdkZ1lEVlIwZkJHOHdiVEJyb0RPZ01ZWXZhSFIwY0RvdkwybHdZUzFqDQpZUzVrWTNObExtMXBiQzVoZFM5cGNHRXZZM0pzTDAxaGMzUmxja05TVEM1aWFXNmlOS1F5TURBeERqQU1CZ05WDQpCQW9NQldsd1lXTmhNUjR3SEFZRFZRUUREQlZEWlhKMGFXWnBZMkYwWlNCQmRYUm9iM0pwZEhrd0hRWURWUjBPDQpCQllFRkM0V09NbENvNFRQZk1QTUlIVXBGYVloRHJGNE1JSEJCZ05WSFJFRWdia3dnYmFDR0doaGNuQjJNREJpDQphWFF3TVM1a1kzTmxMbTFwYkM1aGRZSVZZbWwwWW5WamEyVjBMbVJqYzJVdWJXbHNMbUYxb0RrR0Npc0dBUVFCDQpnamNVQWdPZ0t3d3BTRlJVVUM5b1lYSndkakF3WW1sME1ERXVaR056WlM1dGFXd3VZWFZBUkVOVFJTNU5TVXd1DQpRVldnU0FZR0t3WUJCUUlDb0Q0d1BLQU5Hd3RFUTFORkxrMUpUQzVCVmFFck1DbWdBd0lCQWFFaU1DQWJCRWhVDQpWRkFiR0doaGNuQjJNREJpYVhRd01TNWtZM05sTG0xcGJDNWhkVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBDQpJdXozSU1VTlhtSk9JakJjMDZ5RWROcWdNTUVVcTZsTEUwbzl4RS9WeFpGNEhVZHMrRUxOUm5TbUxkM2ZueGRzDQpsYkZUNG5wQXBkQUlVUExsYVpSSlY4ZzF5UkphcjMza3hsWmdaUUUySUxUb0xycHVYc2xKNkgvS2dGNUtTQjgvDQpPZ2R4eGU1MHZXSTl5Z3JGZS9GczF1SDNUSmRIR0QvN0pMK0NtZmQvUzV1QVZCVEVLTWJVM3c2TFRMVFE5VmFNDQo2VHZ2TlJoTnMxdUU2UVlldkVmVDZFUFJXUmVoZGRIdFFYTFc1cExqOGNlL0tvUHd6bHUwN2NUWHFLQVpBRjFqDQpOZUtXODY3bHdNTmFVUkdYcklpYVU0aTM3TityZldiZWdHTzlWWE9Gb1pURVlJWVVrZmNZK1VoR25PTm9XcWlCDQpIMzg2TTE0cTJ5RWR5UDVHWEtZOWF3PT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg==
            name: bitbucket
  topology:
    controlPlane:
      replicas: 1
      storageClass: sfo01-w01-cl01-vsan-storage-policy
      tkr:
        reference:
          name: v1.20.12---vmware.1-tkg.1.b9a42f3
      vmClass: best-effort-large
    nodePools:
      - name: workers
        replicas: 3
        storageClass: sfo01-w01-cl01-vsan-storage-policy
        tkr:
          reference:
            name: v1.20.12---vmware.1-tkg.1.b9a42f3
        vmClass: best-effort-large
