---
# NOTES:
#   docker network inspect -f '{{.IPAM.Config}}' kind
# [{172.19.0.0/16  172.19.0.1 map[]} {fc00:f853:ccd:e793::/64   map[]}]

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb
  namespace: metallb-system
spec:
  addresses:
    - 172.19.255.1-172.19.255.254

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
