---
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd
  namespace: gpu-operator
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vectoradd
      image: "nvidia/samples:vectoradd-cuda11.2.1"
      resources:
        requests:
          cpu: 2000m
          memory: 2Gi
        limits:
          cpu: 4000m
          memory: 4Gi
          nvidia.com/gpu: "1"
