# rustc --print target-list

##################################################
[build]
##################################################

rustflags = ["-C", "link-args=-lmagic"]

##################################################
[target.x86_64-apple-darwin]
##################################################

linker = "clang"

##################################################
[target.x86_64-unknown-linux-gnu]
##################################################

linker = "gcc"

##################################################
[target.x86_64-unknown-linux-musl]
##################################################

#linker = "musl-gcc"
linker = "x86_64-linux-musl-gcc"

rustflags = ["-C", "target-feature=-crt-static", "-C", "link-args=-static"]

##################################################
[target.armv7-unknown-linux-musleabihf]
##################################################

linker = "arm-linux-gnueabihf-gcc"

##################################################
[target.x86_64-pc-windows-msvc]
##################################################

linker = "msvc"

##################################################
[target.aarch64-unknown-linux-gnu]
##################################################

linker = "aarch64-linux-gnu-gcc"
