##################################################
# Notes
# 	rustc --print target-list
# 	https://doc.rust-lang.org/reference/linkage.html
##################################################

##################################################
[build]
##################################################


##################################################
[rust]
##################################################

channel = "stable"
lld = true

##################################################
[target.x86_64-apple-darwin]
##################################################

linker = "rust-lld"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-unknown-linux-gnu]
##################################################

linker = "rust-lld"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-unknown-linux-musl]
##################################################

linker = "rust-lld"

rustflags = [
	"-C",
	"linker=rust-lld",
	"-C",
	"link-arg=-fuse-ld=lld",
	"-C",
	"link-arg=-mllvm",
	"-C",
	"link-arg=-pnacl-abi-sysroot=/usr/lib/musl",
	"-C",
	"link-arg=-L/usr/lib/musl",
	"-C",
	"link-arg=-lmusl",
	"-C",
	"link-arg=-lgcc_s",
	"-C",
	"link-arg=-lutil",
	"-C",
	"link-arg=-lrt",
	"-C",
	"link-arg=-lpthread",
	"-C",
	"link-arg=-ldl",
	"-C",
	"link-arg=-lc",
]

##################################################
[target.aarch64-unknown-linux-gnu]
##################################################

linker = "rust-lld"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.aarch64-unknown-linux-musl]
##################################################

linker = "rust-lld"

rustflags = [
	"-C",
	"link-arg=-fuse-ld=lld",
	"-C",
	"link-arg=-Tlink.x",
	"-C",
	"link-arg=-m",
	"-C",
	"link-arg=aarch64linux",
	"-C",
	"link-arg=-nostdlib",
	"-C",
	"link-arg=-static",
	"-C",
	"link-arg=crt1.o",
	"-C",
	"link-arg=crti.o",
	"-C",
	"link-arg=crtbegin.o",
	"-C",
	"link-arg=-lc",
	"-C",
	"link-arg=-lgcc",
	"-C",
	"link-arg=-lutil",
	"-C",
	"link-arg=-ldl",
	"-C",
	"link-arg=-lrt",
	"-C",
	"link-arg=-lpthread",
	"-C",
	"link-arg=-lm",
	"-C",
	"link-arg=-lgcc_s",
	"-C",
	"link-arg=crtend.o",
	"-C",
	"link-arg=crtn.o",
]

##################################################
[target.x86_64-pc-windows-gnu]
##################################################

linker = "rust-lld.exe"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-pc-windows-msvc]
##################################################

linker = "rust-lld.exe"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]
