# rustc --print target-list

##################################################
[build]
##################################################

##################################################
[target.x86_64-apple-darwin]
##################################################

linker = "clang"

rustflags = ["-C", "link-arg=-Wl,-dead_strip"]

##################################################
[target.x86_64-unknown-linux-gnu]
##################################################

#linker = "gcc"
linker = "clang"

rustflags = ["-C", "link-arg=-Wl,--gc-sections"]

##################################################
[target.x86_64-unknown-linux-musl]
##################################################

#linker = "musl-gcc"
linker = "musl-clang"

rustflags = [
	"-C",
	"link-arg=-Wl,--gc-sections",
	"-C",
	"target-feature=+crt-static",
]

##################################################
[target.aarch64-unknown-linux-gnu]
##################################################

#linker = "aarch64-linux-gnu-gcc"
linker = "aarch64-linux-gnu-clang"

rustflags = ["-C", "link-arg=-Wl,--gc-sections"]

##################################################
[target.aarch64-unknown-linux-musl]
##################################################

#linker = "aarch64-linux-musl-gcc"
linker = "aarch64-linux-musl-clang"

rustflags = [
	"-C",
	"link-arg=-Wl,--gc-sections",
	"-C",
	"target-feature=+crt-static",
]

##################################################
[target.aarch64-linux-android]
##################################################

linker = "aarch64-linux-android29-clang"

rustflags = ["-C", "link-arg=-Wl,--gc-sections"]

##################################################
[target.x86_64-pc-windows-gnu]
##################################################

#linker = "x86_64-w64-mingw32-gcc"
linker = "x86_64-w64-mingw32-clang"

rustflags = ["-C", "link-arg=-Wl,--gc-sections"]

##################################################
[target.x86_64-pc-windows-msvc]
##################################################

linker = "link.exe"

rustflags = [
	"-C",
	"link-arg=/OPT:REF",
	"-C",
	"link-arg=/OPT:ICF",
	"-C",
	"target-feature=+crt-static",
]
