# rustc --print target-list

##################################################
[build]
##################################################

##################################################
[target.x86_64-apple-darwin]
##################################################

linker = "clang"

##################################################
[target.x86_64-unknown-linux-gnu]
##################################################

linker = "gcc"

##################################################
[target.x86_64-unknown-linux-musl]
##################################################

linker = "rust-lld"

rustflags = ["-C", "target-feature=+crt-static"]

##################################################
[target.aarch64-unknown-linux-gnu]
##################################################

linker = "rust-lld"

rustflags = ["-C", "target-feature=+crt-static"]

##################################################
[target.aarch64-unknown-linux-musl]
##################################################

linker = "rust-lld"

##################################################
[target.x86_64-pc-windows-msvc]
##################################################

linker = "msvc"

rustflags = ["-C", "target-feature=+crt-static"]
