##################################################
# Notes
# 	rustc --print target-list
# 	https://doc.rust-lang.org/reference/linkage.html
##################################################

##################################################
[build]
##################################################


##################################################
[rust]
##################################################

channel = "stable"
lld = true

##################################################
[target.x86_64-apple-darwin]
##################################################

#linker = "rust-lld"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-unknown-linux-gnu]
##################################################

#linker = "rust-lld"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-unknown-linux-musl]
##################################################

linker = "rust-lld"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.aarch64-unknown-linux-gnu]
##################################################

linker = "aarch64-linux-gnu-gcc"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.aarch64-unknown-linux-musl]
##################################################

linker = "rust-lld"

rustflags = [
	"-C",
	"link-arg=-march=armv8-a",
	"-C",
	"link-arg=-mfpu=neon-fp-armv8",
	"-C",
	"link-arg=-mthumb",
	"-C",
	"link-arg=-mcpu=cortex-a53",
	"-C",
	"link-arg=-fuse-ld=lld",
	"-C",
	"link-arg=-lm",
	"-C",
	"link-arg=-ldl",
]

##################################################
[target.x86_64-pc-windows-gnu]
##################################################

#linker = "rust-lld.exe"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-pc-windows-msvc]
##################################################

#linker = "rust-lld.exe"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]
