##################################################
# Notes
# 	rustc --print target-list
# 	https://doc.rust-lang.org/reference/linkage.html
##################################################

##################################################
[target.x86_64-apple-darwin]
##################################################

linker = "clang"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-unknown-linux-gnu]
##################################################

linker = "clang"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-unknown-linux-musl]
##################################################

linker = "clang"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.aarch64-unknown-linux-gnu]
##################################################

linker = "clang"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.aarch64-unknown-linux-musl]
##################################################

linker = "clang"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-pc-windows-gnu]
##################################################

linker = "clang"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]

##################################################
[target.x86_64-pc-windows-msvc]
##################################################

linker = "clang"

rustflags = ["-C", "link-arg=-fuse-ld=lld"]
