##################################################
# Notes
# 	rustc --print target-list
# 	https://doc.rust-lang.org/reference/linkage.html
##################################################

##################################################
[build]
##################################################


##################################################
[rust]
##################################################

channel = "stable"
lld = true

##################################################
[target.x86_64-apple-darwin]
##################################################

##################################################
[target.x86_64-unknown-linux-gnu]
##################################################

##################################################
[target.x86_64-unknown-linux-musl]
##################################################

##################################################
[target.aarch64-unknown-linux-gnu]
##################################################

##################################################
[target.aarch64-unknown-linux-musl]
##################################################

##################################################
[target.x86_64-pc-windows-gnu]
##################################################

#linker = "x86_64-w64-mingw32-gcc"
#ar = "x86_64-w64-mingw32-gcc-ar"

##################################################
[target.x86_64-pc-windows-msvc]
##################################################
