---
log:
  level: debug
  file: /tmp/loopy.log
  fortune: true

dependencies:
  tools:
    - name: helm
      bin: helm
      url: https://get.helm.sh/helm-v3.11.2-linux-amd64.tar.gz
    - name: kubectl
      bin: kubectl
      url: https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
    - name: kind
      bin: kind
      url: https://github.com/kubernetes-sigs/kind/releases/download/v0.17.0/kind-linux-amd64
    - name: cmctl
      bin: cmctl
      url: https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cmctl-linux-amd64.tar.gz

  manifests:
    - name: metallb
      url: https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
      dir: metallb
    - name: cert-manager
      dir: cert-manager
    - name: contour
      dir: contour
    - name: nfs-server
      dir: nfs-server
    - name: postgresql-ha
      dir: postgresql-ha

  helm:
    repositories:
      - name: bitnami
        url: https://charts.bitnami.com/bitnami
      - name: jetstack
        url: https://charts.jetstack.io
      - name: nfs-ganesha
        url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
      - name: ako
        url: https://projects.registry.vmware.com/chartrepo/ako

    charts:
      - name: cert-manager
        repo: bitnami
        values: values-kind.yaml
      - name: contour
        repo: bitnami
        values: values-kind.yaml
      - name: nfs-server-provisioner
        repo: nfs-ganesha
        namespace: nfs-server
        values: values-kind.yaml
      - name: postgresql-ha
        repo: bitnami
        namespace: postgresql
        values: values-kind.yaml

  tests:
    - command: echo "test"
      stdout: "test"
      stderr: ""
    - command: kubectl get ns cert-manager
      stdout: "cert-manager"
      stderr: ""

application:
  manifests:
    - name: cert-authority
      dir: cert-authority
    - name: test
      dir: test

  helm:
    repositories:
    charts:

  tests:
    - command: echo "test"
      stdout: "test"
      stderr: ""
      status: 0
    - command: kubectl get ns cert-manager
      stdout: "cert-manager"
      stderr: ""
      status: 0
