---
log:
  level: debug
  file: /tmp/loopy.log
  fortune: true

dependencies:
  tools:
    - name: helm
      bin: helm
      url: https://get.helm.sh/helm-v3.11.2-linux-amd64.tar.gz
    - name: kubectl
      bin: kubectl
      url: https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
    - name: kind
      bin: kind
      url: https://github.com/kubernetes-sigs/kind/releases/download/v0.17.0/kind-linux-amd64

  manifests:
    - name: metallb
      url: https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
      dir: metallb
    - name: contour
      dir: contour
    - name: test
      dir: test
    #- name: postgresql-ha
    #  dir: postgresql-ha
    #- name: nfs-server-provisioner
    #  dir: nfs-server-provisioner

  helm:
    repositories:
      - name: bitnami
        url: https://charts.bitnami.com/bitnami
      - name: jetstack
        url: https://charts.jetstack.io
      - name: nfs-ganesha
        url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
      - name: ako
        url: https://projects.registry.vmware.com/chartrepo/ako

    charts:
      - name: contour
        repo: bitnami
        namespace: projectcontour
        values: values-http.yaml
      #- name: postgresql-ha
      #  repo: bitnami
      #- name: nfs-server-provisioner
      #  repo: nfs-ganesha

application:
  manifests:
    #- name: ca
    #  dir: certificate-authority
    #- name: bamboo
    #  dir: bamboo
    #- name: bamboo-agent
    #  dir: bamboo-agent
    #- name: bitbucket
    #  dir: bitbucket
    #- name: confluence
    #  dir: confluence
    #- name: crowd
    #  dir: crowd
    #- name: jira
    #  dir: jira

  helm:
    repositories:
      - name: atlassian
        url: https://atlassian.github.io/data-center-helm-charts

    charts:
      #- name: bamboo
      #  repo: atlassian
      #- name: bamboo-agent
      #  repo: atlassian
      #- name: bitbucket
      #  repo: atlassian
      #- name: confluence
      #  repo: atlassian
      #- name: crowd
      #  repo: atlassian
      #- name: jira
      #  repo: atlassian
