---
log:
  level: debug
  file: /tmp/loopy.log
  fortune: true

dependencies:
  tools:
    - name: helm
      bin: helm
      url: https://get.helm.sh/helm-v3.11.2-linux-amd64.tar.gz
    - name: kubectl
      bin: kubectl
      url: https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
    - name: kind
      bin: kind
      url: https://github.com/kubernetes-sigs/kind/releases/download/v0.17.0/kind-linux-amd64

  manifests:
    - name: metallb
      url: https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
      dir: metallb
    - name: contour
      dir: contour
    - name: test
      dir: test

  helm:
    repositories:
      - name: bitnami
        url: https://charts.bitnami.com/bitnami
      - name: jetstack
        url: https://charts.jetstack.io
      - name: nfs-ganesha
        url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
      - name: ako
        url: https://projects.registry.vmware.com/chartrepo/ako

    charts:
      - name: contour
        repo: bitnami
        namespace: projectcontour
        values: values-http.yaml

application:
  manifests:

  helm:
    repositories:

    charts:
