---
# logging configuration
log:
  level: debug
  file: /tmp/loopy.log

# Dependencies are setup prior to installing application packages.
dependencies:
  # A list of dependant tools to check for in the path.
  tools:
    - name: helm
      bin: helm
      url: https://get.helm.sh/helm-v3.11.2-linux-amd64.tar.gz
    - name: kubectl
      bin: kubectl
      url: https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
    - name: kind
      bin: kind
      url: https://github.com/kubernetes-sigs/kind/releases/download/v0.17.0/kind-linux-amd64

  manifests:
    - name: contour-gateway
      url: https://projectcontour.io/quickstart/contour.yaml
    - name: test
      dir: test

  # Helm specific configuration
  helm:
    repositories:
      - name: bitnami
        url: https://charts.bitnami.com/bitnami
      - name: jetstack
        url: https://charts.jetstack.io
      - name: nfs-ganesha
        url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/"
      - name: ako
        url: https://projects.registry.vmware.com/chartrepo/ako

    # A list of helm charts to install.
    charts:
      - name: cert-manager
        repo: bitnami
      - name: contour
        repo: bitnami
      - name: postgresql-ha
        repo: bitnami
      - name: nfs-server-provisioner
        repo: nfs-ganesha
      - name: ako
        repo: ako

    # TODO: Finish Carvel implementation.
    carvel:

# Application specific configuration
application:
  manifests:

  helm:
    repositories:
      - name: atlassian
        url: https://atlassian.github.io/data-center-helm-charts

    # A list of helm chart to install.
    charts:
      - name: bamboo
        repo: atlassian
        values: atlassian-bamboo
      - name: bitbucket
        repo: atlassian
        values: atlassian-bitbucket
      - name: confluence
        repo: atlassian
        values: atlassian-confluence
      - name: crowd
        repo: atlassian
        values: atlassian-crowd
      - name: jira
        repo: atlassian
        values: atlassian-jira

    # TODO: Finish Carvel implementation.
    carvel:
