# NOTE: For development purposes only...
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: atlassian-jira-system-privileged
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - "*"
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
    - max: 65535
      min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "*"

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: atlassian-jira-system-privileged
rules:
  - apiGroups:
      - policy
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - atlassian-system-privileged
      - vmware-system-privileged
    verbs:
      - use

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: atlassian-jirasystem-privileged
  namespace: atlassian-jira
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: atlassian-jira-system-privileged
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - kind: ServiceAccount
    name: default
    namespace: atlassian-jira
  - kind: ServiceAccount
    name: jira
    namespace: atlassian-jira
