---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apt-mirror-frontend
  namespace: apt-mirror
data:
  config.conf: |
    server {
        listen       80;
        listen  [::]:80;

        location / {
            root   /usr/share/nginx/html;
            autoindex on;
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sources-list
  namespace: apt-mirror
data:
  # 20.04
  ubuntu-focal-amd64.list: |
    deb [arch=amd64] http://apt-mirror.saltlabs.tech/os/ubuntu/ focal main restricted universe multiverse
    deb [arch=amd64] http://apt-mirror.saltlabs.tech/os/ubuntu/ focal-updates main restricted universe multiverse
    deb [arch=amd64] http://apt-mirror.saltlabs.tech/os/ubuntu/ focal-backports main restricted universe multiverse
    deb [arch=amd64] http://apt-mirror.saltlabs.tech/os/ubuntu/ focal-security main restricted universe multiverse
  # 22.04
  ubuntu-jammy-amd64.list: |
    deb [arch=amd64] http://apt-mirror.saltlabs.tech/os/ubuntu/ jammy main restricted universe multiverse
    deb [arch=amd64] http://apt-mirror.saltlabs.tech/os/ubuntu/ jammy-updates main restricted universe multiverse
    deb [arch=amd64] http://apt-mirror.saltlabs.tech/os/ubuntu/ jammy-backports main restricted universe multiverse
    deb [arch=amd64] http://apt-mirror.saltlabs.tech/os/ubuntu/ jammy-security main restricted universe multiverse

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-certificates
  namespace: apt-mirror
data:
  au-archive-ubuntu-com.crt: |
    -----BEGIN CERTIFICATE-----
    MIIIGzCCBwOgAwIBAgIQDDPgW60epHoxAa/udIpJnzANBgkqhkiG9w0BAQsFADBP
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMSkwJwYDVQQDEyBE
    aWdpQ2VydCBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTAeFw0yMjEwMDQwMDAwMDBa
    Fw0yMzEwMDQyMzU5NTlaMHMxCzAJBgNVBAYTAkFVMRgwFgYDVQQIEw9OZXcgU291
    dGggV2FsZXMxEjAQBgNVBAcTCUNoYXRzd29vZDEXMBUGA1UEChMOQUFSTkVUIFBU
    WSBMVEQxHTAbBgNVBAMTFG1pcnJvci5hYXJuZXQuZWR1LmF1MIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEAvPc3yIs6HPPEHauKiVOTaQnowNuO4Eb663mo
    wAhI/knm/w4hlTlptIxJpu2oduQDfIts4bdGKHlSGBZe8trT+Dnvf7NmuB4A0bJ/
    wx4ghnEri97tw9SYtxQFc/e9MOJ07ihRL3pNTG78GDXypyov1kZZ8PrVu+3vkRjD
    Tn0gTKYjuYi1oOybYs/mHmwf3SzdivomGDtV3DnaCAfP3wWflV8On2DUy4+zsf1S
    Oz1yElQFvITFN8YiLPlHQ051ErqflxLUKZRPBd2Txl7ttwLTu8Akx5BssFkseOSH
    VMQsVsgpjCZ/FdMfSrX4KsS5qCxIpXMXAoV7XttPfBeKa6y7P3MwNALaSLOmQWCN
    8bfHx6BQkf8Jwx+z8ksatGH6cTiI0NE+shOE6ar3QVJOTHiFFe5riBeAarbLn85g
    5j/Y7mEfexkXEx9q2f7IFLM9aTKHv1tE3dR+u/Ly7+GfpapVjB0XjcZgBNkjUoMe
    BR/6PBJBo0I4h5cXdm0ZnxMdX/1+vIjMqA+kSnGJGALcSxnbxT5l+s//UWQ9jgZ2
    KcegEb/mMKgj70RdbGWi8aMpX0PJiJP2epS4rxl3PKmzDQaMVNfU+dzKwbwP/9Vm
    9loISnmGCeL4DH3v8OYCguUZ9j6OqV8VEXkwoX5t2AeZpsxCFoXLBVYkZCRB4FGu
    kdIcXisCAwEAAaOCA80wggPJMB8GA1UdIwQYMBaAFLdrouqoqoSMeeq02g+YssWV
    drn0MB0GA1UdDgQWBBRSVRmSVrJTS2VPFz/gaVPJ6P+VWjB4BgNVHREEcTBvghRt
    aXJyb3IuYWFybmV0LmVkdS5hdYIXYmlvbWlycm9yLmFhcm5ldC5lZHUuYXWCHnZp
    Yy1wbWxhLW1pcnJvcjEuYWFybmV0Lm5ldC5hdYIeYWN0LWRrc24tbWlycm9yMS5h
    YXJuZXQubmV0LmF1MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcD
    AQYIKwYBBQUHAwIwgY8GA1UdHwSBhzCBhDBAoD6gPIY6aHR0cDovL2NybDMuZGln
    aWNlcnQuY29tL0RpZ2lDZXJ0VExTUlNBU0hBMjU2MjAyMENBMS00LmNybDBAoD6g
    PIY6aHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VExTUlNBU0hBMjU2
    MjAyMENBMS00LmNybDA+BgNVHSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUFBwIB
    FhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwfwYIKwYBBQUHAQEEczBxMCQG
    CCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wSQYIKwYBBQUHMAKG
    PWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRMU1JTQVNIQTI1
    NjIwMjBDQTEtMS5jcnQwCQYDVR0TBAIwADCCAX4GCisGAQQB1nkCBAIEggFuBIIB
    agFoAHYA6D7Q2j71BjUy51covIlryQPTy9ERa+zraeF3fW0GvW4AAAGDoi6zdgAA
    BAMARzBFAiEA2NIfeog2m8mPWB0HYv7ncF7Qqk2q8JlJgBY5x/AMd5sCIBJY3l4w
    g2Vc/EspE085aamXeDVxJb299MUClNCUYmBGAHYAs3N3B+GEUPhjhtYFqdwRCUp5
    LbFnDAuH3PADDnk2pZoAAAGDoi6zrAAABAMARzBFAiEAld5TSr0+pAd6yrIGEzIU
    iChRzwU5blw+MmSN37lCb8wCIA17HIs2ZAecQta8srDVvK5gP5YMK+bcWTafHalI
    7JPDAHYAtz77JN+cTbp18jnFulj0bF38Qs96nzXEnh0JgSXttJkAAAGDoi6zXwAA
    BAMARzBFAiBFa5F1EZyY1nfl1JYUPMOwo1Z7qUONAUkpJILTxCmkeQIhAKgOyVh1
    p/69L3ux+DFgiU+6DxNso1DS3g6i5jboW3M/MA0GCSqGSIb3DQEBCwUAA4IBAQC0
    uj2pE3PymB0HORBRX39C1BdNcc0IzXpGrnJldbPwbClfkgrIg0AK1TQU+YpcoNYA
    awAyrehmcCpEYAqYbgrvVIj5Udo+fCWCMOBoxiDQ9yMgr0Pld3RyfWXq8Rqa+8ss
    hAr3V92rymwsyPlS76PMJyNcNzeblYWbfJY3OmvtsMtRKGahb+5BzrFKxKmpo4a4
    hmsDQrxnXDZlrV/bpb4ecS1KGlv03WyL9PSGS3kRjQlHCeBnX8umYmkjPO9vMKy7
    SxDoNbO7YX9qrBrNHoNuLK/YDZwOd42kQVkz2ekfSpQ12cH7Y8s6vskShaw0o6BZ
    OJzkJfGWL9/vAu9Qt5yD
    -----END CERTIFICATE-----
  digicert-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEvjCCA6agAwIBAgIQBtjZBNVYQ0b2ii+nVCJ+xDANBgkqhkiG9w0BAQsFADBh
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
    QTAeFw0yMTA0MTQwMDAwMDBaFw0zMTA0MTMyMzU5NTlaME8xCzAJBgNVBAYTAlVT
    MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxKTAnBgNVBAMTIERpZ2lDZXJ0IFRMUyBS
    U0EgU0hBMjU2IDIwMjAgQ0ExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAwUuzZUdwvN1PWNvsnO3DZuUfMRNUrUpmRh8sCuxkB+Uu3Ny5CiDt3+PE0J6a
    qXodgojlEVbbHp9YwlHnLDQNLtKS4VbL8Xlfs7uHyiUDe5pSQWYQYE9XE0nw6Ddn
    g9/n00tnTCJRpt8OmRDtV1F0JuJ9x8piLhMbfyOIJVNvwTRYAIuE//i+p1hJInuW
    raKImxW8oHzf6VGo1bDtN+I2tIJLYrVJmuzHZ9bjPvXj1hJeRPG/cUJ9WIQDgLGB
    Afr5yjK7tI4nhyfFK3TUqNaX3sNk+crOU6JWvHgXjkkDKa77SU+kFbnO8lwZV21r
    eacroicgE7XQPUDTITAHk+qZ9QIDAQABo4IBgjCCAX4wEgYDVR0TAQH/BAgwBgEB
    /wIBADAdBgNVHQ4EFgQUt2ui6qiqhIx56rTaD5iyxZV2ufQwHwYDVR0jBBgwFoAU
    A95QNVbRTLtm8KPiGxvDl7I90VUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQG
    CCsGAQUFBwMBBggrBgEFBQcDAjB2BggrBgEFBQcBAQRqMGgwJAYIKwYBBQUHMAGG
    GGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBABggrBgEFBQcwAoY0aHR0cDovL2Nh
    Y2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsUm9vdENBLmNydDBCBgNV
    HR8EOzA5MDegNaAzhjFodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRH
    bG9iYWxSb290Q0EuY3JsMD0GA1UdIAQ2MDQwCwYJYIZIAYb9bAIBMAcGBWeBDAEB
    MAgGBmeBDAECATAIBgZngQwBAgIwCAYGZ4EMAQIDMA0GCSqGSIb3DQEBCwUAA4IB
    AQCAMs5eC91uWg0Kr+HWhMvAjvqFcO3aXbMM9yt1QP6FCvrzMXi3cEsaiVi6gL3z
    ax3pfs8LulicWdSQ0/1s/dCYbbdxglvPbQtaCdB73sRD2Cqk3p5BJl+7j5nL3a7h
    qG+fh/50tx8bIKuxT8b1Z11dmzzp/2n3YWzW2fP9NsarA4h20ksudYbj/NhVfSbC
    EXffPgK2fPOre3qGNm+499iTcc+G33Mw+nur7SpZyEKEOxEXGlLzyQ4UfaJbcme6
    ce1XR2bFuAJKZTRei9AqPCCcUZlM51Ke92sRKw2Sfh3oius2FkOH6ipjv3U/697E
    A7sKPPcw7+uvTPyLNhBzPvOk
    -----END CERTIFICATE-----
  digicert-root-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
    QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
    MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
    b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
    CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
    nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
    43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
    T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
    gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
    BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
    TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
    DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
    hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
    06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
    PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
    YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
    CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
    -----END CERTIFICATE-----

