---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apt-mirror
  namespace: apt-mirror
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: apt-mirror.saltlabs.tech
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apt-mirror-frontend
        app.kubernetes.io/instance: apt-mirror
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: apt-mirror.saltlabs.tech
    spec:
      containers:
        - name: apt-mirror-frontend
          image: harbor.saltlabs.tech/docker.io/caddy:latest
          livenessProbe:
            httpGet:
              path: /liveness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 20
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 250m
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy
            - name: apt-mirror-data
              mountPath: /public
            - name: gpg-keys
              mountPath: /public/keys
            - name: sources-list
              mountPath: /public/sources.list
      volumes:
        - name: apt-mirror-data
          persistentVolumeClaim:
            claimName: apt-mirror-data
        - name: caddyfile
          configMap:
            name: apt-mirror-frontend
            items:
              - key: caddyfile
                path: Caddyfile
        - name: gpg-keys
          secret:
            secretName: gpg-keys
        - name: sources-list
          configMap:
            name: sources-list

