---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apt-mirror
  namespace: apt-mirror
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    projectcontour.io/num-retries: "3"
    projectcontour.io/retry-on: "true"
    projectcontour.io/response-timeout: "15"
    projectcontour.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: apt-mirror.saltlabs.tech
      http:
        paths:
          - backend:
              service:
                name: apt-mirror-frontend
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific

