---
# kubectl cp file.deb pod:/srv/

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apt-mirror-data
  namespace: apt-mirror
  labels:
    app.kubernetes.io/name: apt-mirror-data
    app.kubernetes.io/instance: apt-mirror
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: apt-mirror.saltlabs.tech
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 300Gi
  storageClassName: nfs-server
