---
##################################################
# Name: rust.yml
# Description: Workflow for Rust projects
##################################################

name: Rust

on:
  # A pull request will trigger a build and test.
  pull_request:
    branches:
      - trunk
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested
    paths-ignore:
      - "docs/**"
      - "*.md"

  # A successful completion of this worflow will trigger a release.
  push:
    branches:
      - "trunk"
    paths-ignore:
      - "docs/**"
      - "*.md"

env:
  ORGANISATION: ${{ github.repository_owner }}
  PROJECT: ${{ github.event.repository.name }}

  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  #########################
  # Test the package for linting
  # and ensure formatted correctly
  #########################

  cargo_check:
    name: Cargo Check

    runs-on: ${{ matrix.os }}

    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
            toolchain: stable
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            toolchain: stable
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            toolchain: stable
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            toolchain: stable
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            toolchain: stable
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            toolchain: stable
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            toolchain: stable

    steps:
      - id: setup_rust
        name: Setup the Rust environment
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - id: setup_zig
        name: Setup the Zig environment
        uses: goto-bus-stop/setup-zig@v2

      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          persist-credentials: true

      - id: cache_artifacts_cargo_registry
        name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-${{ matrix.target }}-${{ matrix.toolchain }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-${{ matrix.toolchain }}-cargo-registry-

      - id: cache_artifacts_cargo_index
        name: Cache Cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-${{ matrix.target }}-${{ matrix.toolchain }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-${{ matrix.toolchain }}-cargo-registry-

      - id: cache_artifacts_cargo_target
        name: Cache Cargo build
        uses: actions/cache@v2
        with:
          path: target/release
          key: ${{ runner.os }}-${{ matrix.target }}-${{ matrix.toolchain }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-${{ matrix.toolchain }}-cargo-registry-

      - id: cache_artifacts_vcpkg
        name: Cache vcpkg
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v2
        with:
          path: vcpkg
          key: ${{ runner.os }}-${{ matrix.target }}-${{ matrix.toolchain }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-${{ matrix.toolchain }}-cargo-registry-

      - id: setup_rust_linux_common
        name: Setup the Rust environment
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            autoconf \
            automake \
            binutils \
            build-essential \
            ca-certificates \
            clang \
            cmake \
            curl \
            file \
            g++ \
            gcc \
            git \
            libc6-dev \
            libgcc-10-dev \
            libgcc1 \
            librust-libm-dev \
            libmagic-dev \
            libmagic1 \
            libpq-dev \
            libpthread-stubs0-dev \
            libssl-dev \
            libtool \
            lld \
            llvm \
            make \
            pkgconf \
            rust-all \
            wget \
            xutils-dev \
            zlib1g-dev \
            zstd

      - id: setup_rust_x86_64-apple-darwin
        name: Setup the Rust environment for x86_64-apple-darwin
        if: matrix.target == 'x86_64-apple-darwin' && matrix.os == 'macos-latest'
        run: |
          brew update
          brew install \
            bzip2 \
            figlet \
            file \
            gnu-tar \
            libmagic \
            openssl \
            pkg-config \
            zlib \
            zstd

      - id: setup_rust_x86_64-unknown-linux-gnu
        name: Setup the Rust environment for x86_64-unknown-linux-gnu
        if: matrix.target == 'x86_64-unknown-linux-gnu' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-multilib \
            g++-multilib

      - id: setup_rust_x86_64-unknown-linux-musl
        name: Setup the Rust environment for x86_64-unknown-linux-musl
        if: matrix.target == 'x86_64-unknown-linux-musl' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            musl \
            musl-dev \
            musl-tools

      - id: setup_rust_aarch64_unknown_linux_gnu
        name: Setup the Rust environment for aarch64-unknown-linux-gnu
        if: matrix.target == 'aarch64-unknown-linux-gnu' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            binutils-aarch64-linux-gnu \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu

      - id: setup_rust_aarch64_unknown_linux_musl
        name: Setup the Rust environment for aarch64-unknown-linux-musl
        if: matrix.target == 'aarch64-unknown-linux-musl' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            binutils-aarch64-linux-gnu \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            musl \
            musl-dev \
            musl-tools
          wget https://musl.cc/aarch64-linux-musl-cross.tgz
          tar -xzf aarch64-linux-musl-cross.tgz -C /opt/
          echo "PATH=/opt/aarch64-linux-musl-cross/bin:$PATH" >> "${GITHUB_ENV}"

      - id: setup_rust_windows
        name: Setup the Rust environment for Windows
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          cargo install cargo-vcpkg
          cargo vcpkg --verbose build

      - id: setup_msys2_windows
        name: Install MSYS2 packages on Windows
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          platform-check-severity: fatal
          update: true
          release: true
          msystem: CLANG64
          install: >-
            base-devel
            git
            mingw-w64-x86_64-perl

      - id: run_msys2_windows
        name: Run MSYS2 commands on Windows
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          cpan Pod::Usage
          echo "PERL5LIB=$(perl -e 'print "@INC"'):$PERL5LIB" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - id: setup_zigbuild
        name: Setup Zig Build
        run: |
          cargo install cargo-zigbuild

      - id: setup_xwin
        name: Setup XWin Build
        run: |
          cargo install cargo-xwin

      - id: cargo_check
        name: Run Cargo check
        run: |
          cargo --version
          cargo check --verbose --target ${{ matrix.target }}

      - id: cargo_fmt
        name: Run Cargo format
        run: |
          rustup component add rustfmt
          rustup component list --toolchain ${{ matrix.toolchain }}
          cargo fmt --version
          cargo fmt --all -- --check

      - id: cargo_clippy
        name: Run Cargo clippy
        run: |
          rustup component add clippy
          rustup component list --toolchain ${{ matrix.toolchain }}
          cargo clippy --version
          cargo clippy --all --all-features --target ${{ matrix.target }} -- -D warnings

      - id: cargo_zigbuild
        name: Run Zig Build
        run: |
          cargo zigbuild --verbose --target ${{ matrix.target }} --release

      - id: cargo_xwin
        name: Run XWin Build
        if: matrix.os != 'windows-latest' && matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          cargo xwin build --verbose --target ${{ matrix.target }} --release

      - id: cargo_test
        name: Run Cargo tests
        run: |
          cargo --version
          cargo test --verbose

      - id: archive_rust
        name: Archive Rust artifacts (cross-platform)
        if: >-
          github.event_name == 'push' &&
          github.ref == 'refs/heads/${{ env.BRANCH_NAME_DEFAULT}}'
        shell: pwsh
        working-directory: "${{ github.workspace }}"
        run: >
          ./.github/scripts/archive.ps1
          -Target ${{ matrix.target }}
          -LogLevel debug
          -DieHard
          -OutputDir artifacts

      - id: upload_artifacts
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.PROJECT }}-${{ matrix.target }}
          path: artifacts/${{ env.PROJECT }}-${{ matrix.target }}.zip
          retention-days: 7
