---
##################################################
# Name: thumbs.yaml
# Description:
#   A Workflow that posts Thumbs Up/Down comments.
##################################################

name: Thumbs Up/Down

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read
  checks: read
  deployments: read
  statuses: read

env:
  ORGANISATION: ${{ github.repository_owner }}
  PROJECT: ${{ github.event.repository.name }}

  # Works on pushes or PRs
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

jobs:
  wait_linter:
    name: Wait for Linter

    runs-on: ${{ matrix.os }}

    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: wait_for_linter
        name: Wait for Linter (${{ matrix.os }})
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: GitHub Super-Linter (${{ matrix.os }})
          timeoutSeconds: 1800
          intervalSeconds: 30

    outputs:
      conclusion: ${{ steps.wait_for_linter.outputs.conclusion }}

  wait_rust:
    name: Wait for Rust

    runs-on: ${{ matrix.os }}

    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            toolchain: stable
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            toolchain: stable
          - target: x86_64-apple-darwin
            os: macos-latest
            toolchain: stable
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            toolchain: stable
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            toolchain: stable
        #exclude:

    steps:
      - id: wait_for_rust
        name: Wait for Rust (${{ matrix.target }}, ${{ matrix.os }}, ${{ matrix.toolchain }})
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: Cargo Test (${{ matrix.target }}, ${{ matrix.os }}, ${{ matrix.toolchain }})
          timeoutSeconds: 1800
          intervalSeconds: 30

    outputs:
      conclusion: ${{ steps.wait_for_rust.outputs.conclusion }}

  comment:
    name: Thumbs

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    needs:
      - wait_linter
      - wait_rust

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: pr_comment_thumbs_up
        name: PR Comment (Thumbs Up)
        if: ${{ needs.wait_linter.outputs.conclusion == 'success' && needs.wait_rust.outputs.conclusion == 'success' }}
        uses: exercism/pr-commenter-action@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/pr-comments/thumbs_up.yaml
          template-variables: |
            {
              "id": "${{ github.sha }}-thumbs",
              "onCreate": "create",
              "onUpdate": "recreate"
            }

      - id: pr_comment_thumbs_down
        name: PR Comment (Thumbs Down)
        if: ${{ needs.wait_linter.outputs.conclusion != 'success' || needs.wait_rust.outputs.conclusion != 'success' }}
        uses: exercism/pr-commenter-action@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/pr-comments/thumbs_down.yaml
          template-variables: |
            {
              "id": "${{ github.sha }}-thumbs",
              "onCreate": "create",
              "onUpdate": "recreate"
            }
